name: "Generate ReadyAPI People"
description: "Generate the data for the ReadyAPI People page"
author: "KhulnaSoft Ltd <info@khulnasoft.com>"
inputs:
  token:
    description: "User token, to read the GitHub API. Can be passed in using {{ secrets.PEOPLE_TOKEN }}"
    required: true
  standard_token:
    description: "Default GitHub Action token, used for the PR. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
